<div style="width:1000 px">



<h1>NumPy Basics</h1>


<div style="clear:both"></div>
</div>

<hr style="height:2px;">

<div style="float:right; width:250 px"><img src="http://www.contribute.geeksforgeeks.org/wp-content/uploads/numpy-logo1.jpg" alt="NumPy Logo" style="height: 250px;"></div>

- NumPy provides the numerical backend for nearly every scientific or technical library for Python. 
-  In fact, NumPy is the foundation library for scientific computing in Python since it provides data structures and high-performing functions that the basic Python standard library cannot provide. 
- Therefore, knowledge of this library is essential in terms of numerical calculations since its correct use can greatly influence the performance of your computations.



NumPy contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- useful linear algebra, Fourier transform, and random number capabilities

The NumPy array object is the common interface for working with typed arrays of data across a wide-variety of scientific Python packages. NumPy also features a C-API, which enables interfacing existing Fortran/C/C++ libraries with Python and NumPy.

## Getting Help with NumPy

Here are some important resources for learning more about NumPy and getting help.

- [NumPy Documentation](https://docs.scipy.org/doc/numpy/reference/)
- [NumPy Official User Guide](http://docs.scipy.org/doc/numpy/user/)
- [NCAR Hackathons NumPy Guide](https://ncar-hackathons.github.io/scientific-computing/numpy/intro.html)
- [NumPy GitHub Issue Tracker](https://github.com/numpy/numpy/issues)
- [NumPy questions on StackOverflow](https://stackoverflow.com/questions/tagged/numpy)



## Learning Objectives


1. Array Data Structure
2. Slice and index the array
3. Computations with Arrays
4. Array Broadcasting



_Note: This notebook heavily borrows from the following original sources:_

- https://github.com/Unidata/python-workshop
- [NumPy Tutorial @ 2017 Scipy Conference](https://github.com/enthought/Numpy-Tutorial-SciPyConf-2017)

## Array Data Structure


The NumPy array represents a *contiguous* block of memory, holding entries of a given type (and hence fixed size). The entries are laid out in memory according to the shape, or list of dimension sizes.

In [1]:
# Convention for import to get shortened namespace
import numpy as np

In [2]:
# Create a simple array from a list of floats
a = np.array([0., 1., 2., 3., 4., 5., 6., 7., 8.]).reshape(3, 3)
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

![arr](./img/array.png)

In [3]:
# See how many dimensions the array has
a.ndim

2

In [4]:
# Print out the shape attribute
a.shape

(3, 3)

In [5]:
# Print out the data type attribute
a.dtype

dtype('float64')

In [6]:
# Print out the strides of the array
a.strides

(24, 8)

**Note:** Strides attribute is a tuple of bytes to step in each dimension when traversing an array.

In [7]:
# This time use a list of integers
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [8]:
# See how many dimensions the array has
a.ndim

1

In [9]:
# Print out the shape attribute
a.shape

(5,)

In [10]:
# Print out the data type attribute
a.dtype

dtype('int64')

NumPy also provides helper functions for generating arrays of data to save you typing for regularly spaced data. 

* `arange(start, stop, interval)` creates a range of values in the interval `[start,stop)` with `step` spacing.
* `linspace(start, stop, num)` creates a range of `num` evenly spaced values over the range `[start,stop]`.

### arange

In [11]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [12]:
a = np.arange(3, 11)
print(a)

[ 3  4  5  6  7  8  9 10]


In [13]:
a = np.arange(1, 10, 2)
print(a)

[1 3 5 7 9]


### linspace

In [14]:
b = np.linspace(5, 15, 5)
print(b)

[ 5.   7.5 10.  12.5 15. ]


In [15]:
b = np.linspace(2.5, 10.25, 11)
print(b)

[ 2.5    3.275  4.05   4.825  5.6    6.375  7.15   7.925  8.7    9.475
 10.25 ]


## Perform basic calculations with Python

### Basic math

In core Python, that is *without* NumPy, creating sequences of values and adding them together requires writing a lot of manual loops, just like one would do in C/C++:

In [16]:
a = range(5, 10)
b = [3 + i * 1.5/4 for i in range(5)]

In [17]:
result = []
for x, y in zip(a, b):
    result.append(x + y)
print(result)

[8.0, 9.375, 10.75, 12.125, 13.5]


That is very verbose and not very intuitive. Using NumPy this becomes:

In [18]:
a = np.arange(5, 10)
b = np.linspace(3, 4.5, 5)

In [19]:
a + b

array([ 8.   ,  9.375, 10.75 , 12.125, 13.5  ])

The four major mathematical operations operate in the same way. They perform an element-by-element calculation of the two arrays. The two must be the same shape though!

In [20]:
a * b

array([15.  , 20.25, 26.25, 33.  , 40.5 ])

### Constants

NumPy provides us access to some useful constants as well - remember you should never be typing these in manually! Other libraries such as SciPy and MetPy have their own set of constants that are more domain specific.

In [21]:
np.pi

3.141592653589793

In [22]:
np.e

2.718281828459045

In [23]:
# This makes working with radians effortless!
t = np.arange(0, 2 * np.pi + np.pi / 4, np.pi / 4)
t

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265,
       3.92699082, 4.71238898, 5.49778714, 6.28318531])

## Index and slice arrays

Indexing is how we pull individual data items out of an array. Slicing extends this process to pulling out a regular set of the items.

In [24]:
# Create an array for testing
a = np.arange(12).reshape(3, 4)

In [25]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Indexing in Python is 0-based, so the command below looks for the 2nd item along the first dimension (row) and the 3rd along the second dimension (column).



![](./img/array_index.png)

In [26]:
a[1, 2]

6

Can also just index on one dimension

In [27]:
a[2]

array([ 8,  9, 10, 11])

Negative indices are also allowed, which permit indexing relative to the end of the array.

In [28]:
a[0, -1]

3

Slicing syntax is written as `start:stop[:step]`, where all numbers are optional.
- defaults: 
  - start = 0
  - stop = len(dim)
  - step = 1
- The second colon is also optional if no step is used.

It should be noted that end represents one past the last item; one can also think of it as a half open interval: `[start, end)`

In [29]:
# Get the 2nd and 3rd rows
a[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
# All rows and 3rd column
a[:, 2]

array([ 2,  6, 10])

In [31]:
# ... can be used to replace one or more full slices
a[..., 2]

array([ 2,  6, 10])

In [32]:
# Slice every other row
a[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

#### Exerise 1

Create a NumPy array `x` with 

```python
x = np.arange(25).reshape(5, 5)
```

and extract the slices as indicated:

![](./img/slicing.png)

In [33]:
x_yellow = None
x_red = None
x_blue = None

In [34]:
# %load solutions/numpy/exercise1.py

## Computation with Arrays

When doing computation with NumPy arrays the following happens:

- Operations between multiple array objects are first checked for proper shape match 
- Mathematical operators (`+`, `*`, `/`, `-`, `exp`, `log`, ...) apply element by element, on the values
- Reduction operations (`mean`, `std`, `sum`, `kurt`, `prod`, ...) apply to the whole array, unless an axis is specified.
- Missing values propagate unless explicitly ignored (`nanmean`, `nansum`, ...)

###  Array math functions

NumPy also has math functions that can operate on arrays. Similar to the math operations, these greatly simplify and speed up these operations. Be sure to checkout the [listing](https://docs.scipy.org/doc/numpy/reference/routines.math.html) of mathematical functions in the NumPy documentation.

In [35]:
# Calculate the sine function
sin_t = np.sin(t)
print(sin_t)

[ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01
  1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
 -2.44929360e-16]


In [36]:
# Round to three decimal places
print(np.round(sin_t, 3))

[ 0.     0.707  1.     0.707  0.    -0.707 -1.    -0.707 -0.   ]


In [37]:
# Calculate the cosine function
cos_t = np.cos(t)
print(cos_t)

[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00 -7.07106781e-01 -1.83697020e-16  7.07106781e-01
  1.00000000e+00]


In [38]:
# Convert radians to degrees
degrees = np.rad2deg(t)
print(degrees)

[  0.  45.  90. 135. 180. 225. 270. 315. 360.]


In [39]:
# Integrate the sine function with the trapezoidal rule
sine_integral = np.trapz(sin_t, t)
print(np.round(sine_integral, 3))

-0.0


In [40]:
# Sum the values of the cosine
cos_sum = np.sum(cos_t)
print(cos_sum)

0.9999999999999996


In [41]:
# Calculate the cumulative sum of the cosine
cos_csum = np.cumsum(cos_t)
print(cos_csum)

[ 1.00000000e+00  1.70710678e+00  1.70710678e+00  1.00000000e+00
  0.00000000e+00 -7.07106781e-01 -7.07106781e-01 -4.44089210e-16
  1.00000000e+00]


###  Statistics functions

NumPy also has statistics functions that can operate on arrays. Be sure to checkout the [listing](https://docs.scipy.org/doc/numpy/reference/routines.statistics.html) of statistics functions in the NumPy documentation.

In [42]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
# compute the mean values of each column
a.mean(axis=0)

array([2.5, 3.5, 4.5])

In [44]:
np.mean(a, axis=0)

array([2.5, 3.5, 4.5])

In [45]:
# Standard deviation
a.std(axis=0)

array([1.5, 1.5, 1.5])

In [46]:
# Standard deviation for sample, set ddof=1
a.std(axis=0, ddof=1)

array([2.12132034, 2.12132034, 2.12132034])

#### Exericise 2:

Create the array below with 

```python
a = np.arange(-15, 15).reshape(5, 6) ** 2
```
and compute:

- The maximum of each row (one max per row)
- The mean of each column (one mean per column)
- The position of the overall minimum (requireds 2-3 steps)

In [47]:
a = np.arange(-15, 15).reshape(5, 6) ** 2
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]])

In [48]:
# %load solutions/numpy/exercise2.py

## Array Broadcasting

NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are **broadcasted** to match the larger arrays, **without copying the data**.

Broadcasting has **two rules**:
    
### Rule 1: Prepend Ones to Smaller Array's Shape

In [49]:
a = np.ones((3, 5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
a.shape

(3, 5)

In [51]:
b = np.ones((5, ))
b

array([1., 1., 1., 1., 1.])

In [52]:
b.shape

(5,)

In [53]:
b.reshape(1, 5) # The result is a (1, 5)-shaped array

array([[1., 1., 1., 1., 1.]])

In [54]:
b[np.newaxis, :] # equivalent, more concise

array([[1., 1., 1., 1., 1.]])

### Rule 2: Dimension of Size 1 are Repeated Without Copying

In [55]:
c = a + b

In [56]:
c.shape

(3, 5)

The above is logically equivalent to:

In [57]:
tmp_b = b.reshape(1, 5)
tmp_b_repeat = tmp_b.repeat(3, axis=0)
c = a + tmp_b_repeat
c

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

But broadcasting makes no copies of **`b`**'s data

![broadcasting](./img/broadcasting.png)